name: test

run-name: ${{ github.actor }} is a test flow

on: [push]

jobs:
  checkout-repository:
    runs-on: self-hosted
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

  load-env:
    uses: ./.github/workflows/load-env.yml

### BUILD ###
  build-core:
    needs: [checkout-repository, load-env]
    uses: ./.github/workflows/build-rgl.yml
    with:
      build-command: ./setup.py --build-dir build-core
      self-hosted-user-id: ${{ needs.load-env.outputs.user-id }}
      optix-install-dir: ${{ needs.load-env.outputs.optix-install-dir }}

  build-pcl:
    needs: [checkout-repository, load-env]
    uses: ./.github/workflows/build-rgl.yml
    with:
      build-command: ./setup.py --with-pcl --build-dir build-pcl
      self-hosted-user-id: ${{ needs.load-env.outputs.user-id }}
      optix-install-dir: ${{ needs.load-env.outputs.optix-install-dir }}

### TEST IN RGL DOCKER ###
  test-core:
    needs: [build-core]
    uses: ./.github/workflows/test-rgl.yml
    with:
      test-command: cd build-core/test && ./RobotecGPULidar_test
      docker-image: localhost:5000/rgl:latest

  test-pcl:
    needs: [ build-pcl ]
    uses: ./.github/workflows/test-rgl.yml
    with:
      test-command: cd build-pcl/test && ./RobotecGPULidar_test
      docker-image: localhost:5000/rgl:latest

### TEST IN CLEAN DOCKER ###
  test-on-clean-machine-core:
    needs: [build-core]
    uses: ./.github/workflows/test-rgl.yml
    with:
      test-command: cd build-core/test && ./RobotecGPULidar_test
      docker-image: nvidia/cuda:11.7.1-base-ubuntu22.04

#  build:
#    needs: [checkout-repository, load-env]
#    runs-on: self-hosted
#    steps:
#      - name: build core
#        uses: ./.github/workflows/build-rgl.yml
#        with:
#          RGL_BUILD_COMMAND: ./setup.py --build-dir build-core
#
#      - name: build pcl extension
#        uses: ./.github/workflows/build-rgl.yml
#        with:
#          RGL_BUILD_COMMAND: ./setup.py --with-pcl --build-dir build-pcl

#  build-rgl-base:
#    needs: [checkout-repository, load-env]
#    runs-on: self-hosted
#    container:
#      image: docker://localhost:5000/rgl:latest
#      env:
#        OptiX_INSTALL_DIR: /optix
#        NVIDIA_DRIVER_CAPABILITIES: all
#      volumes:
#        - ${{ needs.load-env.outputs.optix-install-dir }}:/optix
#      options:
#        --gpus all
#        --user ${{ needs.load-env.outputs.user-id }}
#    steps:
#      - name: fix git
#        run: git config --global --add safe.directory $PWD
#      - name: build
#        run: ./setup.py --build-dir build-core
#
#  build-rgl-with-pcl:
#    needs: [ checkout-repository, load-env ]
#    runs-on: self-hosted
#    container:
#      image: docker://localhost:5000/rgl:latest
#      env:
#        OptiX_INSTALL_DIR: /optix
#        NVIDIA_DRIVER_CAPABILITIES: all
#      volumes:
#        - ${{ needs.load-env.outputs.optix-install-dir }}:/optix
#      options:
#        --gpus all
#        --user ${{ needs.load-env.outputs.user-id }}
#    steps:
#      - name: fix git
#        run: git config --global --add safe.directory $PWD
#      - name: build
#        run: ./setup.py --with-pcl --build-dir build-pcl
