name: test

run-name: ${{ github.actor }} is a test flow

on: [push]

jobs:
  load-env:
    uses: ./.github/workflows/load-env.yml

  checkout-repository:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

  build:
    needs: [checkout-repository, load-env]
    runs-on: self-hosted
    steps:
      - name: build core
        uses: ./.github/workflows/build-rgl.yml
        with:
          RGL_BUILD_COMMAND: ./setup.py --build-dir build-core

      - name: build pcl extension
        uses: ./.github/workflows/build-rgl.yml
        with:
          RGL_BUILD_COMMAND: ./setup.py --with-pcl --build-dir build-pcl

#  build-rgl-base:
#    needs: [checkout-repository, load-env]
#    runs-on: self-hosted
#    container:
#      image: docker://localhost:5000/rgl:latest
#      env:
#        OptiX_INSTALL_DIR: /optix
#        NVIDIA_DRIVER_CAPABILITIES: all
#      volumes:
#        - ${{ needs.load-env.outputs.optix-install-dir }}:/optix
#      options:
#        --gpus all
#        --user ${{ needs.load-env.outputs.user-id }}
#    steps:
#      - name: fix git
#        run: git config --global --add safe.directory $PWD
#      - name: build
#        run: ./setup.py --build-dir build-core
#
#  build-rgl-with-pcl:
#    needs: [ checkout-repository, load-env ]
#    runs-on: self-hosted
#    container:
#      image: docker://localhost:5000/rgl:latest
#      env:
#        OptiX_INSTALL_DIR: /optix
#        NVIDIA_DRIVER_CAPABILITIES: all
#      volumes:
#        - ${{ needs.load-env.outputs.optix-install-dir }}:/optix
#      options:
#        --gpus all
#        --user ${{ needs.load-env.outputs.user-id }}
#    steps:
#      - name: fix git
#        run: git config --global --add safe.directory $PWD
#      - name: build
#        run: ./setup.py --with-pcl --build-dir build-pcl
