name: test

run-name: ${{ github.actor }} is a test flow

on: [push]

jobs:
  checkout-repository:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

#  build-rgl-host:
#    needs: checkout-repository
#    runs-on: self-hosted
#    steps:
#      - run: ./setup.py --build-dir build-host

  build-rgl-docker:
    needs: checkout-repository
    runs-on: self-hosted
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    container:
      image: localhost:5000/rgl:latest
      env:
        NVIDIA_DRIVER_CAPABILITIES: all
      volumes:
        - $PWD:/code
      options:
        --rm
        --name rgl
        --gpus all
    steps:
      - run: ./setup.py --build-dir build-docker
